import type { ArrayStep } from '../../engine/types/Step';
import type { QuizCheckpoint, QuizQuestion , QuizRevisionData } from '../../engine/types/Quiz';
import { buildOptions } from '../../engine/types/Quiz';

type DPAlgorithmKey = 'fibonacciDP' | 'coinChange' | 'houseRobber' | 'knapsack01' | 'lcs' | 'lis' | 'editDistance' | 'uniquePaths';

/* ── Anchor data per algorithm ────────────────────────────────────────── */

interface Anchor {
  prompt: string;
  correct: string;
  distractors: string[];
  explanation: string;
  hint: string;
  concept: string;
}

const ANCHORS: Record<DPAlgorithmKey, Anchor[]> = {
  fibonacciDP: [
    {
      prompt: 'What is the recurrence relation for Fibonacci in a standard DP solution?',
      correct: 'dp[i] = dp[i-1] + dp[i-2]',
      distractors: [
        'dp[i] = dp[i-1] * dp[i-2]',
        'dp[i] = dp[i-1] + i',
        'dp[i] = 2 * dp[i-1]',
      ],
      explanation:
        'Each Fibonacci value is the sum of the two preceding values, with base cases such as dp[0] = 0 and dp[1] = 1.',
      hint: 'Each term depends on the previous two terms.',
      concept: 'Recurrence relation',
    },
    {
      prompt: 'What are the usual base cases for Fibonacci DP?',
      correct: 'dp[0] = 0 and dp[1] = 1',
      distractors: [
        'dp[0] = 1 and dp[1] = 1',
        'dp[0] = 0 and dp[1] = 0',
        'dp[0] = 1 and dp[1] = 0',
      ],
      explanation:
        'The standard Fibonacci sequence starts with 0 and 1. Later values are generated by adding the previous two values.',
      hint: 'Recall the first two Fibonacci numbers.',
      concept: 'Base cases',
    },
    {
      prompt: 'Why is bottom-up Fibonacci DP faster than naive recursive Fibonacci?',
      correct: 'Previously computed values are reused instead of recomputed',
      distractors: [
        'It changes Fibonacci into a constant-time problem',
        'It skips all odd indices',
        'It uses sorting to reduce recursion',
      ],
      explanation:
        'Naive recursion repeatedly solves the same subproblems. DP stores each result and reuses it.',
      hint: 'Think about overlapping subproblems.',
      concept: 'Memoization / reuse',
    },
    {
      prompt: 'What is the typical time complexity of bottom-up Fibonacci DP?',
      correct: 'O(n)',
      distractors: [
        'O(log n)',
        'O(n²)',
        'O(2^n)',
      ],
      explanation:
        'The bottom-up solution computes each dp position once, so it takes linear time.',
      hint: 'How many dp positions are calculated?',
      concept: 'Time complexity',
    },
    {
      prompt: 'What is the space optimization for Fibonacci DP when only the final value is needed?',
      correct: 'Keep only the previous two Fibonacci values',
      distractors: [
        'Store all n values in a table',
        'Store all recursive call stacks',
        'Sort the Fibonacci values',
      ],
      explanation:
        'Because dp[i] depends only on dp[i-1] and dp[i-2], the whole table is unnecessary when only the final result is required.',
      hint: 'How many earlier values does the recurrence actually use?',
      concept: 'Space optimization',
    },
  ],

  coinChange: [
    {
      prompt: 'What does dp[i] represent in the minimum Coin Change problem?',
      correct: 'The minimum number of coins needed to make amount i',
      distractors: [
        'The maximum number of coins needed to make amount i',
        'The number of distinct ways to make amount i',
        'Whether amount i is prime',
      ],
      explanation:
        'The state stores the minimum number of coins required to form each amount.',
      hint: 'This is an optimization problem: minimize the coin count.',
      concept: 'State definition',
    },
    {
      prompt: 'What is the natural base case for Coin Change when solving for amount 0?',
      correct: 'dp[0] = 0',
      distractors: [
        'dp[0] = 1',
        'dp[0] = infinity',
        'dp[0] = -1',
      ],
      explanation:
        'Zero coins are required to make amount zero, so dp[0] is zero.',
      hint: 'How many coins are needed to make nothing?',
      concept: 'Base case',
    },
    {
      prompt: 'What does an unreachable amount mean in the Coin Change DP table?',
      correct: 'No available combination of coins can form that amount',
      distractors: [
        'The amount automatically requires one coin',
        'The amount must use every coin exactly once',
        'The amount is always handled by greedy choice',
      ],
      explanation:
        'If no transition can produce an amount, its dp value remains the chosen unreachable sentinel such as infinity.',
      hint: 'Ask what it means when no valid transition exists.',
      concept: 'Unreachable state',
    },
    {
      prompt: 'Why does Coin Change DP consider multiple possible final coins for an amount?',
      correct: 'Different last coins can lead to different subproblem solutions',
      distractors: [
        'Every coin has the same value',
        'Only the largest coin can be used',
        'The algorithm must sort all coins after every step',
      ],
      explanation:
        'For each amount, the solution may end with different coin choices. DP compares these alternatives and keeps the minimum.',
      hint: 'Think about all possible choices for the last coin.',
      concept: 'State transition',
    },
    {
      prompt: 'What is the common time complexity of the basic Coin Change DP with n amounts and m coin types?',
      correct: 'O(nm)',
      distractors: [
        'O(n + m)',
        'O(n²m²)',
        'O(log(nm))',
      ],
      explanation:
        'Each amount is examined against each coin type, giving O(nm) time.',
      hint: 'Think about the nested amount × coin loops.',
      concept: 'Time complexity',
    },
  ],

  houseRobber: [
    {
      prompt: 'Why can the robber not simply rob every other house?',
      correct: 'The optimal choice depends on house values, not a fixed position pattern',
      distractors: [
        'Houses are never indexed',
        'Adjacent houses are always allowed',
        'The problem requires robbing exactly half the houses',
      ],
      explanation:
        'A fixed alternating pattern may miss a more valuable non-adjacent combination.',
      hint: 'Compare house values, not just positions.',
      concept: 'Optimal substructure',
    },
    {
      prompt: 'What is the key recurrence for the House Robber problem?',
      correct: 'dp[i] = max(dp[i-1], dp[i-2] + value[i])',
      distractors: [
        'dp[i] = dp[i-1] + value[i]',
        'dp[i] = min(dp[i-1], dp[i-2])',
        'dp[i] = dp[i-1] * value[i]',
      ],
      explanation:
        'At each house, either skip it and keep dp[i-1], or rob it and add its value to dp[i-2].',
      hint: 'There are two choices: skip or rob.',
      concept: 'Recurrence',
    },
    {
      prompt: 'Why does robbing house i force the algorithm to use dp[i-2] rather than dp[i-1]?',
      correct: 'The immediately previous house cannot also be robbed',
      distractors: [
        'House i-1 always has value zero',
        'The array skips every other value automatically',
        'dp[i-1] contains a sorting result',
      ],
      explanation:
        'Adjacent houses cannot both be selected, so the best compatible state ends at i-2.',
      hint: 'What does the adjacency restriction forbid?',
      concept: 'Constraint',
    },
    {
      prompt: 'What is the time complexity of the standard House Robber DP?',
      correct: 'O(n)',
      distractors: [
        'O(log n)',
        'O(n²)',
        'O(2^n)',
      ],
      explanation:
        'Each house is processed once with constant-time state updates.',
      hint: 'How many times is each house considered?',
      concept: 'Time complexity',
    },
    {
      prompt: 'What is a useful space optimization for House Robber when only the final maximum is required?',
      correct: 'Keep only the previous two DP values',
      distractors: [
        'Store all subsets of houses',
        'Keep a matrix of all house combinations',
        'Use recursion without storing any state',
      ],
      explanation:
        'The recurrence only depends on dp[i-1] and dp[i-2], so two rolling values are sufficient.',
      hint: 'Look at the recurrence dependencies.',
      concept: 'Space optimization',
    },
  ],

  knapsack01: [
    {
      prompt: 'What does dp[i][w] represent in 0/1 Knapsack?',
      correct: 'Maximum value using the first i items with capacity w',
      distractors: [
        'Total weight of the first i items',
        'Whether item i must be selected',
        'Number of items that fit in capacity w',
      ],
      explanation:
        'The state records both how many items have been considered and the available capacity.',
      hint: 'The state needs an item dimension and a capacity dimension.',
      concept: 'State definition',
    },
    {
      prompt: 'Why is it called 0/1 Knapsack?',
      correct: 'Each item can be chosen either zero times or one time',
      distractors: [
        'Each item must be chosen exactly once',
        'Only items with values 0 and 1 are allowed',
        'Each item has a binary weight',
      ],
      explanation:
        'For each item, the decision is take it once or do not take it.',
      hint: 'Think binary choice: take or skip.',
      concept: 'Problem constraint',
    },
    {
      prompt: 'What happens when an item is too heavy for the current capacity?',
      correct: 'The item cannot be taken, so inherit the value from the previous item set',
      distractors: [
        'Take it anyway',
        'Increase the capacity automatically',
        'Reset the whole DP table',
      ],
      explanation:
        'If weight[i] > w, the item is infeasible for that capacity, so dp[i][w] = dp[i-1][w].',
      hint: 'Can an item heavier than the remaining capacity be selected?',
      concept: 'Feasibility',
    },
    {
      prompt: 'When an item fits, which two possibilities are compared?',
      correct: 'Skip the item versus take it and add its value to the compatible previous state',
      distractors: [
        'Take it twice versus skip it',
        'Sort versus reverse the items',
        'Use current value versus current weight',
      ],
      explanation:
        'The optimal transition compares excluding the item with including it once and using remaining capacity.',
      hint: 'There are exactly two choices for a 0/1 item.',
      concept: 'State transition',
    },
    {
      prompt: 'What is the usual time complexity of the standard 0/1 Knapsack DP?',
      correct: 'O(nW)',
      distractors: [
        'O(n + W)',
        'O(n²)',
        'O(2^W)',
      ],
      explanation:
        'The table has n item rows and W capacity states, and each state is computed in constant time.',
      hint: 'Count the number of DP states.',
      concept: 'Time complexity',
    },
  ],

  lcs: [
    {
      prompt: 'What is the key recurrence when the current characters match in LCS?',
      correct: 'dp[i][j] = dp[i-1][j-1] + 1',
      distractors: [
        'dp[i][j] = dp[i-1][j] + dp[i][j-1]',
        'dp[i][j] = 0',
        'dp[i][j] = dp[i-1][j-1] - 1',
      ],
      explanation:
        'A matching pair can extend the common subsequence by one character.',
      hint: 'A match lets both prefixes advance together.',
      concept: 'Match recurrence',
    },
    {
      prompt: 'What happens in LCS when the current characters do not match?',
      correct: 'Take the maximum of dropping one character from either string',
      distractors: [
        'Always set the cell to zero',
        'Add both characters to the LCS',
        'Restart the entire table',
      ],
      explanation:
        'When characters differ, the optimal LCS either excludes the current character of the first string or the second string.',
      hint: 'Mismatch creates two possible prefix choices.',
      concept: 'Mismatch recurrence',
    },
    {
      prompt: 'What is the usual time complexity of the classic 2D LCS DP?',
      correct: 'O(nm)',
      distractors: [
        'O(n + m)',
        'O(n² + m²) regardless of n and m',
        'O(log(nm))',
      ],
      explanation:
        'The DP table contains n × m states, each computed in constant time.',
      hint: 'How many string-index pairs exist?',
      concept: 'Time complexity',
    },
    {
      prompt: 'What does dp[i][j] typically represent in LCS?',
      correct: 'Length of the LCS of the first i characters of s1 and first j characters of s2',
      distractors: [
        'The number of matching positions only',
        'The length of the longest common substring',
        'The number of distinct subsequences',
      ],
      explanation:
        'The state works on prefixes, which enables the recurrence to reuse smaller subproblems.',
      hint: 'Think prefixes, not arbitrary positions.',
      concept: 'State definition',
    },
    {
      prompt: 'Why is LCS not the same as longest common substring?',
      correct: 'A subsequence may skip characters while preserving order; a substring must be contiguous',
      distractors: [
        'LCS ignores character order',
        'Substring can skip arbitrary characters',
        'Both require contiguous matches',
      ],
      explanation:
        'LCS preserves relative order but allows gaps. A substring requires consecutive characters.',
      hint: 'Focus on whether gaps are allowed.',
      concept: 'Problem distinction',
    },
  ],

  lis: [
    {
      prompt: 'What does dp[i] represent in the classic O(n²) LIS DP?',
      correct: 'Length of the longest increasing subsequence ending at index i',
      distractors: [
        'Length of the entire LIS immediately',
        'The value of arr[i]',
        'Number of increasing subsequences starting at i',
      ],
      explanation:
        'Each dp[i] describes the best increasing subsequence whose final element is arr[i].',
      hint: 'The state is tied to where the subsequence ends.',
      concept: 'State definition',
    },
    {
      prompt: 'When can j extend an increasing subsequence ending at i?',
      correct: 'When arr[j] < arr[i]',
      distractors: [
        'When arr[j] > arr[i]',
        'Only when arr[j] == arr[i]',
        'Whenever j is adjacent to i',
      ],
      explanation:
        'For an increasing subsequence, the previous value must be smaller than the current value.',
      hint: 'The values must increase from j to i.',
      concept: 'Extension condition',
    },
    {
      prompt: 'What is the recurrence when arr[j] < arr[i] in the standard LIS DP?',
      correct: 'dp[i] = max(dp[i], dp[j] + 1)',
      distractors: [
        'dp[i] = dp[j] - 1',
        'dp[i] = dp[i] + arr[j]',
        'dp[i] = 0',
      ],
      explanation:
        'A valid predecessor j can extend its subsequence by appending arr[i].',
      hint: 'Extending a subsequence increases its length by one.',
      concept: 'State transition',
    },
    {
      prompt: 'How is the final LIS length obtained from the O(n²) DP table?',
      correct: 'Take the maximum value among all dp[i]',
      distractors: [
        'Use only dp[0]',
        'Use dp[n-1] in every input',
        'Sum all dp[i] values',
      ],
      explanation:
        'The longest increasing subsequence may end at any index, so the maximum over all endpoints is the answer.',
      hint: 'The best subsequence does not have to end at the last array element.',
      concept: 'Final answer',
    },
    {
      prompt: 'What is the usual time complexity of the classic LIS DP?',
      correct: 'O(n²)',
      distractors: [
        'O(n)',
        'O(log n)',
        'O(2^n)',
      ],
      explanation:
        'For each i, the algorithm can compare against all previous j values.',
      hint: 'Think about the nested i and j loops.',
      concept: 'Time complexity',
    },
  ],

  editDistance: [
    {
      prompt: 'What are the three standard operations in Levenshtein Edit Distance?',
      correct: 'Insert, delete, and replace one character',
      distractors: [
        'Swap, reverse, and delete',
        'Insert, duplicate, and shift',
        'Replace a word, delete a word, and insert a word',
      ],
      explanation:
        'Levenshtein distance allows single-character insertion, deletion, or replacement, each with unit cost in the classic formulation.',
      hint: 'Think character-level edits.',
      concept: 'Operations',
    },
    {
      prompt: 'What does dp[i][j] represent in Edit Distance?',
      correct: 'Minimum edits needed to transform the first i characters into the first j characters',
      distractors: [
        'Number of matching characters',
        'Maximum edits possible between the prefixes',
        'Length of the longest common substring',
      ],
      explanation:
        'The DP state measures the minimum transformation cost between two prefixes.',
      hint: 'It stores the cheapest transformation cost.',
      concept: 'State definition',
    },
    {
      prompt: 'What happens when the current characters match in Edit Distance?',
      correct: 'No new edit cost is added, and the solution uses dp[i-1][j-1]',
      distractors: [
        'Always add one replacement',
        'Delete both characters',
        'Reset the cell to zero',
      ],
      explanation:
        'Matching characters already agree, so the optimal cost is inherited from the two shorter prefixes.',
      hint: 'A match needs no operation.',
      concept: 'Match case',
    },
    {
      prompt: 'What is done when the current characters differ?',
      correct: 'Take the minimum of insert, delete, and replace transitions plus one',
      distractors: [
        'Always replace regardless of cost',
        'Always delete the first character',
        'Take the maximum transition',
      ],
      explanation:
        'A mismatch can be handled by three legal operations, so DP chooses the cheapest resulting subproblem.',
      hint: 'Three operations, one unit of cost.',
      concept: 'Mismatch case',
    },
    {
      prompt: 'What is the usual time complexity of the classic Edit Distance DP?',
      correct: 'O(nm)',
      distractors: [
        'O(n + m)',
        'O(n² + m²) for every input',
        'O(2^n)',
      ],
      explanation:
        'The DP table contains one state for each pair of prefix lengths.',
      hint: 'Count the number of (i, j) states.',
      concept: 'Time complexity',
    },
  ],

  uniquePaths: [
    {
      prompt: 'What is the recurrence for the number of unique paths to an interior grid cell?',
      correct: 'dp[i][j] = dp[i-1][j] + dp[i][j-1]',
      distractors: [
        'dp[i][j] = dp[i-1][j] * dp[i][j-1]',
        'dp[i][j] = dp[i-1][j-1] + 1',
        'dp[i][j] = dp[i][j] + dp[i-1][j+1]',
      ],
      explanation:
        'With only right and down moves, every path to an interior cell must arrive from either above or left.',
      hint: 'There are two possible predecessor cells.',
      concept: 'Recurrence',
    },
    {
      prompt: 'What is the usual base value for cells in the first row when only right/down moves are allowed?',
      correct: '1 — there is only one way along the row',
      distractors: [
        '0 for every first-row cell',
        'The column index',
        'The number of diagonal paths',
      ],
      explanation:
        'Along the first row, the robot can only keep moving right, so exactly one path reaches each cell.',
      hint: 'Can you move down when you are already in the first row?',
      concept: 'Boundary condition',
    },
    {
      prompt: 'Why can the first column also be initialized with 1s?',
      correct: 'There is only one path down the first column',
      distractors: [
        'Every cell has two predecessors',
        'Diagonal movement is always allowed',
        'The first column is ignored by DP',
      ],
      explanation:
        'Along the first column, the only possible movement is downward.',
      hint: 'There is no left move from the first column.',
      concept: 'Boundary condition',
    },
    {
      prompt: 'What does dp[i][j] represent in Unique Paths?',
      correct: 'The number of valid paths from the start to cell (i,j)',
      distractors: [
        'The minimum path cost',
        'The number of obstacles in the row',
        'The Manhattan distance only',
      ],
      explanation:
        'The DP table counts how many right/down paths can reach each cell.',
      hint: 'This is a counting problem, not an optimization problem.',
      concept: 'State definition',
    },
    {
      prompt: 'What is the usual time complexity of the 2D Unique Paths DP?',
      correct: 'O(rows × columns)',
      distractors: [
        'O(rows + columns) regardless of table size',
        'O(2^(rows + columns))',
        'O(log(rows × columns))',
      ],
      explanation:
        'Each grid cell is computed once from its neighbors.',
      hint: 'Count the number of cells.',
      concept: 'Time complexity',
    },
  ],
};

/* ── Mid-execution question generators ────────────────────────────────── */

function getMidQuestion(
  algorithm: DPAlgorithmKey,
  step: ArrayStep,
  _stepIndex: number
): QuizQuestion {
  const { variables = {} } = step;

  switch (algorithm) {
    case 'fibonacciDP': {
      const i = typeof variables.i === 'number' ? variables.i : 2;
      const dpI1 = typeof variables['dp[i-1]'] === 'number' ? variables['dp[i-1]'] : 0;
      const dpI2 = typeof variables['dp[i-2]'] === 'number' ? variables['dp[i-2]'] : 0;
      const expected = (dpI1 as number) + (dpI2 as number);
      const id = `dp-${algorithm}-mid`;
      const built = buildOptions(id, `${expected}`, [`${expected + 1}`, `${expected - 1}`, `${(dpI1 as number) * 2}`]);
      return {
        id,
        prompt: `Computing dp[${i}] = dp[${i - 1}] + dp[${i - 2}] = ${dpI1} + ${dpI2}. What is dp[${i}]?`,
        options: built.options,
        correctIndex: built.correctIndex,
        explanation: `dp[${i}] = ${dpI1} + ${dpI2} = ${expected}.`,
        hint: 'Just add the two preceding dp values.',
        concept: 'Recurrence computation',
        weight: 2,
      };
    }

    case 'coinChange': {
      const i = typeof variables.i === 'number' ? variables.i : 1;
      const dpI = typeof variables['dp[i]'] === 'number' ? variables['dp[i]'] : 0;
      const id = `dp-${algorithm}-mid`;
      const built = buildOptions(id, `dp[${i}] is finalized`, ['dp array is reset', 'All coins are used', 'Amount is unreachable']);
      return {
        id,
        prompt: `After processing amount ${i}, what happens next in the algorithm?`,
        options: built.options,
        correctIndex: built.correctIndex,
        explanation: `After trying all coins for amount ${i}, dp[${i}] = ${dpI} is finalized and the algorithm moves to amount ${i + 1}.`,
        hint: 'The outer loop iterates over amounts one by one.',
        concept: 'Loop progression',
        weight: 2,
      };
    }

    case 'houseRobber': {
      const i = typeof variables.i === 'number' ? variables.i : 2;
      const dpI1 = typeof variables['dp[i-1]'] === 'number' ? variables['dp[i-1]'] : 0;
      const dpI2 = typeof variables['dp[i-2]'] === 'number' ? variables['dp[i-2]'] : 0;
      const housesI = typeof variables['houses[i]'] === 'number' ? variables['houses[i]'] : 0;
      const skip = dpI1;
      const take = (dpI2 as number) + (housesI as number);
      const id = `dp-${algorithm}-mid`;
      const correct = take > skip ? `Rob house ${i}: ${take}` : `Skip house ${i}: ${skip}`;
      const wrong = take > skip ? `Skip house ${i}: ${skip}` : `Rob house ${i}: ${take}`;
      const built = buildOptions(id, correct, [wrong, `Rob both adjacent houses`, 'Reset dp to zero']);
      return {
        id,
        prompt: `At house ${i}: skip gives ${skip}, take gives ${take}. Which is chosen?`,
        options: built.options,
        correctIndex: built.correctIndex,
        explanation: `dp[${i}] = max(dp[${i - 1}], dp[${i - 2}] + houses[${i}]) = max(${skip}, ${take}) = ${Math.max(skip, take)}.`,
        hint: 'Compare the value of skipping vs taking the current house.',
        concept: 'State transition',
        weight: 2,
      };
    }

    case 'knapsack01': {
      const i = typeof variables.i === 'number' ? variables.i : 1;
      const w = typeof variables.w === 'number' ? variables.w : 0;
      const wi = typeof variables.wi === 'number' ? variables.wi : 0;
      const id = `dp-${algorithm}-mid`;
      const canTake = w >= wi;
      const built = buildOptions(
        id,
        canTake ? 'Consider both taking and skipping the item' : 'Skip the item (too heavy for this capacity)',
        [
          canTake ? 'Skip the item (too heavy for this capacity)' : 'Consider both taking and skipping the item',
          'Take the item regardless of weight',
          'Move to the next row',
        ]
      );
      return {
        id,
        prompt: `Item ${i} (weight ${wi}), current capacity w=${w}. What does the algorithm do?`,
        options: built.options,
        correctIndex: built.correctIndex,
        explanation: canTake
          ? `Since weight ${wi} <= capacity ${w}, we compare taking (dp[i-1][w-wi]+vi) vs skipping (dp[i-1][w]).`
          : `Since weight ${wi} > capacity ${w}, we cannot take this item, so dp[i][w] = dp[i-1][w].`,
        hint: 'Check if the item fits before deciding.',
        concept: 'Item decision',
        weight: 2,
      };
    }

    case 'lcs': {
      const i = typeof variables.i === 'number' ? variables.i : 1;
      const j = typeof variables.j === 'number' ? variables.j : 1;
      const s1 = typeof variables.s1 === 'string' ? variables.s1 : '';
      const s2 = typeof variables.s2 === 'string' ? variables.s2 : '';
      const match = s1[i - 1] === s2[j - 1];
      const id = `dp-${algorithm}-mid`;
      const built = buildOptions(
        id,
        match ? 'Characters match: dp[i][j] = dp[i-1][j-1] + 1' : 'Characters differ: dp[i][j] = max(dp[i-1][j], dp[i][j-1])',
        [
          match ? 'Characters differ: dp[i][j] = max(dp[i-1][j], dp[i][j-1])' : 'Characters match: dp[i][j] = dp[i-1][j-1] + 1',
          'Reset dp[i][j] to zero',
          'Skip both characters',
        ]
      );
      return {
        id,
        prompt: `Comparing s1[${i - 1}]='${s1[i - 1] || '?'}' with s2[${j - 1}]='${s2[j - 1] || '?'}'. What happens?`,
        options: built.options,
        correctIndex: built.correctIndex,
        explanation: match
          ? `The characters match, so dp[${i}][${j}] = dp[${i - 1}][${j - 1}] + 1.`
          : `The characters differ, so dp[${i}][${j}] = max(dp[${i - 1}][${j}], dp[${i}][${j - 1}]).`,
        hint: 'Match extends the subsequence; mismatch takes the best alternative.',
        concept: 'Character comparison',
        weight: 2,
      };
    }

    case 'lis': {
      const i = typeof variables.i === 'number' ? variables.i : 1;
      const j = typeof variables.j === 'number' ? variables.j : 0;
      const arrI = typeof variables['arr[i]'] === 'number' ? variables['arr[i]'] : 0;
      const arrJ = typeof variables['arr[j]'] === 'number' ? variables['arr[j]'] : 0;
      const extend = (arrJ as number) < (arrI as number);
      const id = `dp-${algorithm}-mid`;
      const built = buildOptions(
        id,
        extend ? `Extend: dp[${i}] = max(dp[${i}], dp[${j}]+1)` : `Skip j=${j}: arr[${j}]=${arrJ} >= arr[${i}]=${arrI}`,
        [
          extend ? `Skip j=${j}: arr[${j}]=${arrJ} >= arr[${i}]=${arrI}` : `Extend: dp[${i}] = max(dp[${i}], dp[${j}]+1)`,
          'Reset dp[i] to 0',
          'Move to the next outer loop iteration',
        ]
      );
      return {
        id,
        prompt: `Checking j=${j} for i=${i}: arr[${j}]=${arrJ} vs arr[${i}]=${arrI}. What happens?`,
        options: built.options,
        correctIndex: built.correctIndex,
        explanation: extend
          ? `arr[${j}]=${arrJ} < arr[${i}]=${arrI}, so we can extend the subsequence ending at j. dp[${i}] may increase.`
          : `arr[${j}]=${arrJ} >= arr[${i}]=${arrI}, so j cannot precede i in an increasing subsequence. Skip.`,
        hint: 'For LIS, we need arr[j] < arr[i] to extend.',
        concept: 'Extension check',
        weight: 2,
      };
    }

    case 'editDistance': {
      const i = typeof variables.i === 'number' ? variables.i : 1;
      const j = typeof variables.j === 'number' ? variables.j : 1;
      const s1 = typeof variables.s1 === 'string' ? variables.s1 : '';
      const s2 = typeof variables.s2 === 'string' ? variables.s2 : '';
      const match = s1[i - 1] === s2[j - 1];
      const id = `dp-${algorithm}-mid`;
      const built = buildOptions(
        id,
        match ? 'No edit needed: dp[i][j] = dp[i-1][j-1]' : 'Choose min of insert, delete, replace + 1',
        [
          match ? 'Choose min of insert, delete, replace + 1' : 'No edit needed: dp[i][j] = dp[i-1][j-1]',
          'Skip this cell entirely',
          'Always replace the character',
        ]
      );
      return {
        id,
        prompt: `s1[${i - 1}]='${s1[i - 1] || '?'}' vs s2[${j - 1}]='${s2[j - 1] || '?'}'. What is dp[${i}][${j}]?`,
        options: built.options,
        correctIndex: built.correctIndex,
        explanation: match
          ? 'Characters match, so no operation is needed. dp[i][j] = dp[i-1][j-1].'
          : 'Characters differ, so we pick the cheapest of insert, delete, or replace (each +1).',
        hint: 'A match costs 0; a mismatch costs 1 plus the best subproblem.',
        concept: 'Edit operation',
        weight: 2,
      };
    }

    case 'uniquePaths': {
      const i = typeof variables.i === 'number' ? variables.i : 1;
      const j = typeof variables.j === 'number' ? variables.j : 1;
      const dpAbove = typeof variables['dp[above]'] === 'number' ? variables['dp[above]'] : 0;
      const dpLeft = typeof variables['dp[left]'] === 'number' ? variables['dp[left]'] : 0;
      const expected = (dpAbove as number) + (dpLeft as number);
      const id = `dp-${algorithm}-mid`;
      const built = buildOptions(id, `${expected}`, [`${expected + 1}`, `${(dpAbove as number) * 2}`, `${dpLeft}`]);
      return {
        id,
        prompt: `dp[${i}][${j}] = dp[${i - 1}][${j}] + dp[${i}][${j - 1}] = ${dpAbove} + ${dpLeft}. What is dp[${i}][${j}]?`,
        options: built.options,
        correctIndex: built.correctIndex,
        explanation: `dp[${i}][${j}] = ${dpAbove} + ${dpLeft} = ${expected}.`,
        hint: 'Sum the paths from above and from the left.',
        concept: 'Path counting',
        weight: 2,
      };
    }
  }
}

/* ── Main adapter entry point ────────────────────────────────────────── */

export function buildDPCheckpoints(
  steps: ArrayStep[],
  algorithm: DPAlgorithmKey
): QuizCheckpoint[] {
  if (steps.length < 2) return [];

  const checkpoints: QuizCheckpoint[] = [];
  // One fixed conceptual question at step 0.
  // Selection is deterministic so quiz generation stays reproducible.
  const anchors = ANCHORS[algorithm];
  const anchorIndex = steps.length % anchors.length;
  const anchor = anchors[anchorIndex];

  const anchorId = `dp-${algorithm}-anchor-${anchorIndex}`;
  const anchorOptions = buildOptions(anchorId, anchor.correct, anchor.distractors);
  checkpoints.push({
    stepIndex: 0,
    question: {
      id: anchorId,
      prompt: anchor.prompt,
      options: anchorOptions.options,
      correctIndex: anchorOptions.correctIndex,
      explanation: anchor.explanation,
      hint: anchor.hint,
      concept: anchor.concept,
      weight: 1,
    },
  });

  // Mid-execution question at ~40% of steps
  if (steps.length > 5) {
    const midIdx = Math.floor(steps.length * 0.4);
    const midStep = steps[midIdx];
    const midQ = getMidQuestion(algorithm, midStep, midIdx);
    checkpoints.push({ stepIndex: midIdx, question: midQ });
  }

  // Late-execution reinforcement at ~75% for larger executions
  if (steps.length > 12) {
    const lateIdx = Math.floor(steps.length * 0.75);
    const lateStep = steps[lateIdx];
    const lateQ = getMidQuestion(algorithm, lateStep, lateIdx);
    lateQ.id = `${lateQ.id}-late`;
    lateQ.weight = 3;
    checkpoints.push({ stepIndex: lateIdx, question: lateQ });
  }

  return checkpoints;
}

/* ── Revision data ─────────────────────────────────────────────────── */

const REVISION_DATA: Record<DPAlgorithmKey, QuizRevisionData> = {
  fibonacciDP: {
    description: 'Compute Fibonacci numbers using dynamic programming',
    complexity: 'O(n) time, O(n) space',
    keyIdea: 'Store previously computed values to avoid redundant recalculation',
    watchFor: ['Recurrence relation', 'Base cases', 'Space optimization'],
    quickTip: 'Only need dp[i-1] and dp[i-2]—can optimize space to O(1) with two variables',
    example: 'dp[0]=0, dp[1]=1, dp[2]=1, dp[3]=2, dp[4]=3, dp[5]=5. Each value is the sum of the two before it.',
  },
  coinChange: {
    description: 'Find minimum coins needed to make a target amount',
    complexity: 'O(amount × coins) time, O(amount) space',
    keyIdea: 'dp[i] = min(dp[i - coin] + 1) for all coin denominations',
    watchFor: ['State definition', 'Transition', 'Unreachable amount handling'],
    quickTip: 'Initialize dp array with infinity—dp[0] = 0; if dp[amount] stays infinity, it is impossible',
    example: 'Coins [1,5,10], amount=12: dp[12] = min(dp[11]+1, dp[7]+1, dp[2]+1) = min(11+1, 2+1, 2+1) = 3 coins (10+1+1 or 5+5+1+1... no, 10+1+1).',
  },
  houseRobber: {
    description: 'Maximize robbed value without robbing adjacent houses',
    complexity: 'O(n) time, O(n) space',
    keyIdea: 'dp[i] = max(dp[i-1], dp[i-2] + house[i])—skip current or take it',
    watchFor: ['State transition', 'Non-adjacency constraint', 'Space optimization'],
    quickTip: 'At each house, choose: skip it (keep dp[i-1]) or rob it (dp[i-2] + house[i])',
    example: 'Houses [2,7,9,3,1]: dp=[2,7,11,11,12]. At house 2 (val=9): max(dp[1]=7, dp[0]+9=11) = 11. Answer: 12.',
  },
  knapsack01: {
    description: 'Maximize value in a knapsack with 0/1 item choices',
    complexity: 'O(n × capacity) time, O(n × capacity) space',
    keyIdea: 'dp[i][w] = max(dp[i-1][w], dp[i-1][w-weight[i]] + value[i])',
    watchFor: ['2D state', 'Item inclusion decision', 'Space optimization to 1D'],
    quickTip: 'Process items one by one—for each, decide: skip (take above cell) or take (add value to cell at reduced weight)',
    example: 'Items [(w=2,v=3),(w=3,v=4),(w=4,v=5)], capacity=5: best is items 1+2 with weight 5, value 7.',
  },
  lcs: {
    description: 'Find the longest common subsequence of two strings',
    complexity: 'O(m × n) time, O(m × n) space',
    keyIdea: 'If characters match, extend LCS; otherwise take the best of skipping one character from either string',
    watchFor: ['Match vs mismatch', 'Diagonal vs adjacent cells', 'Reconstruction'],
    quickTip: 'Match: dp[i][j] = dp[i-1][j-1] + 1; mismatch: dp[i][j] = max(dp[i-1][j], dp[i][j-1])',
    example: 's1="ABCBDAB", s2="BDCAB": LCS is "BCAB" (length 4). Match at B,C,A,B positions.',
  },
  lis: {
    description: 'Find the length of the longest increasing subsequence',
    complexity: 'O(n²) time, O(n) space',
    keyIdea: 'dp[i] = length of LIS ending at index i; check all j < i where arr[j] < arr[i]',
    watchFor: ['O(n²) DP vs O(n log n) patience sort', 'Extension condition', 'Max over all dp[i]'],
    quickTip: 'Answer is max(dp[i]) over all i—not necessarily dp[n-1]',
    example: 'Array [10,9,2,5,3,7,101,18]: dp=[1,1,1,2,2,3,4,4]. LIS length is 4 (e.g. [2,5,7,101]).',
  },
  editDistance: {
    description: 'Find minimum edits to transform one string into another',
    complexity: 'O(m × n) time, O(m × n) space',
    keyIdea: 'Match costs 0; mismatch costs 1 + min(insert, delete, replace)',
    watchFor: ['Three operations', 'Match shortcut', 'Base cases (empty strings)'],
    quickTip: 'If chars match, dp[i][j] = dp[i-1][j-1]; else dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])',
    example: 's1="kitten", s2="sitting": edit distance = 3 (replace k→s, replace e→i, insert g).',
  },
  uniquePaths: {
    description: 'Count unique paths from top-left to bottom-right in a grid',
    complexity: 'O(m × n) time, O(m × n) space',
    keyIdea: 'dp[i][j] = dp[i-1][j] + dp[i][j-1]—paths come from above or left',
    watchFor: ['Recurrence', 'Base cases (first row/col)', 'Space optimization'],
    quickTip: 'First row and first column all have 1 path—every other cell sums paths from above and left',
    example: '3×3 grid: dp=[[1,1,1],[1,2,3],[1,3,6]]. Answer = 6 paths from top-left to bottom-right.',
  },
};

export function buildRevisionData(key: DPAlgorithmKey): QuizRevisionData {
  return REVISION_DATA[key];
}
