export type LLCodeLanguage =
  | 'python'
  | 'cpp'
  | 'java'
  | 'javascript'
  | 'go'
  | 'rust'
  | 'csharp'
  | 'ruby'
  | 'pseudocode';

export interface LLCodeSnippets {
  [language: string]: string[];
}

export const LINKED_LIST_SNIPPETS: Record<string, LLCodeSnippets> = {
  singly_insert_head: {
    python: [
      'def insert_head(head, val):',
      '    new_node = ListNode(val)',
      '    new_node.next = head',
      '    head = new_node',
      '    return head',
    ],
    cpp: [
      'ListNode* insertHead(ListNode* head, int val) {',
      '    ListNode* newNode = new ListNode(val);',
      '    newNode->next = head;',
      '    head = newNode;',
      '    return head;',
      '}',
    ],
    java: [
      'public ListNode insertHead(ListNode head, int val) {',
      '    ListNode newNode = new ListNode(val);',
      '    newNode.next = head;',
      '    head = newNode;',
      '    return head;',
      '}',
    ],
    javascript: [
      'function insertHead(head, val) {',
      '    const newNode = new ListNode(val);',
      '    newNode.next = head;',
      '    head = newNode;',
      '    return head;',
      '}',
    ],
    go: [
      'func insertHead(head *ListNode, val int) *ListNode {',
      '    newNode := &ListNode{Val: val, Next: head}',
      '    return newNode',
      '}',
    ],
    rust: [
      'pub fn insert_head(head: Option<Box<ListNode>>, val: i32) -> Option<Box<ListNode>> {',
      '    Some(Box::new(ListNode { val, next: head }))',
      '}',
    ],
    pseudocode: [
      'function insertHead(head, value):',
      '    newNode ← new Node(value)',
      '    newNode.next ← head',
      '    head ← newNode',
      '    return head',
    ],
  },

  reverse: {
    python: [
      'def reverse_list(head):',
      '    prev, curr = None, head',
      '    while curr:',
      '        next_node = curr.next',
      '        curr.next = prev',
      '        prev = curr',
      '        curr = next_node',
      '    return prev',
    ],
    cpp: [
      'ListNode* reverseList(ListNode* head) {',
      '    ListNode *prev = nullptr, *curr = head;',
      '    while (curr != nullptr) {',
      '        ListNode* next = curr->next;',
      '        curr->next = prev;',
      '        prev = curr;',
      '        curr = next;',
      '    }',
      '    return prev;',
      '}',
    ],
    java: [
      'public ListNode reverseList(ListNode head) {',
      '    ListNode prev = null, curr = head;',
      '    while (curr != null) {',
      '        ListNode next = curr.next;',
      '        curr.next = prev;',
      '        prev = curr;',
      '        curr = next;',
      '    }',
      '    return prev;',
      '}',
    ],
    javascript: [
      'function reverseList(head) {',
      '    let prev = null, curr = head;',
      '    while (curr !== null) {',
      '        const next = curr.next;',
      '        curr.next = prev;',
      '        prev = curr;',
      '        curr = next;',
      '    }',
      '    return prev;',
      '}',
    ],
    go: [
      'func reverseList(head *ListNode) *ListNode {',
      '    var prev *ListNode',
      '    curr := head',
      '    for curr != nil {',
      '        next := curr.Next',
      '        curr.Next = prev',
      '        prev = curr',
      '        curr = next',
      '    }',
      '    return prev',
      '}',
    ],
    rust: [
      'pub fn reverse_list(mut head: Option<Box<ListNode>>) -> Option<Box<ListNode>> {',
      '    let mut prev = None;',
      '    while let Some(mut curr) = head {',
      '        head = curr.next.take();',
      '        curr.next = prev;',
      '        prev = Some(curr);',
      '    }',
      '    prev',
      '}',
    ],
    pseudocode: [
      'function reverseList(head):',
      '    prev ← NULL, curr ← head',
      '    while curr ≠ NULL do',
      '        next ← curr.next',
      '        curr.next ← prev',
      '        prev ← curr',
      '        curr ← next',
      '    return prev',
    ],
  },

  detect_cycle: {
    python: [
      'def has_cycle(head):',
      '    slow, fast = head, head',
      '    while fast and fast.next:',
      '        slow = slow.next',
      '        fast = fast.next.next',
      '        if slow == fast:',
      '            return True  # Cycle detected',
      '    return False',
    ],
    cpp: [
      'bool hasCycle(ListNode *head) {',
      '    ListNode *slow = head, *fast = head;',
      '    while (fast && fast->next) {',
      '        slow = slow->next;',
      '        fast = fast->next->next;',
      '        if (slow == fast) return true;',
      '    }',
      '    return false;',
      '}',
    ],
    java: [
      'public boolean hasCycle(ListNode head) {',
      '    ListNode slow = head, fast = head;',
      '    while (fast != null && fast.next != null) {',
      '        slow = slow.next;',
      '        fast = fast.next.next;',
      '        if (slow == fast) return true;',
      '    }',
      '    return false;',
      '}',
    ],
    javascript: [
      'function hasCycle(head) {',
      '    let slow = head, fast = head;',
      '    while (fast && fast.next) {',
      '        slow = slow.next;',
      '        fast = fast.next.next;',
      '        if (slow === fast) return true;',
      '    }',
      '    return false;',
      '}',
    ],
    go: [
      'func hasCycle(head *ListNode) bool {',
      '    slow, fast := head, head',
      '    for fast != nil && fast.Next != nil {',
      '        slow = slow.Next',
      '        fast = fast.Next.Next',
      '        if slow == fast { return true }',
      '    }',
      '    return false',
      '}',
    ],
    pseudocode: [
      'function hasCycle(head):',
      '    slow ← head, fast ← head',
      '    while fast ≠ NULL and fast.next ≠ NULL do',
      '        slow ← slow.next',
      '        fast ← fast.next.next',
      '        if slow = fast then return true',
      '    return false',
    ],
  },

  middle_node: {
    python: [
      'def find_middle(head):',
      '    slow, fast = head, head',
      '    while fast and fast.next:',
      '        slow = slow.next',
      '        fast = fast.next.next',
      '    return slow',
    ],
    cpp: [
      'ListNode* middleNode(ListNode* head) {',
      '    ListNode *slow = head, *fast = head;',
      '    while (fast && fast->next) {',
      '        slow = slow->next;',
      '        fast = fast->next->next;',
      '    }',
      '    return slow;',
      '}',
    ],
    java: [
      'public ListNode middleNode(ListNode head) {',
      '    ListNode slow = head, fast = head;',
      '    while (fast != null && fast.next != null) {',
      '        slow = slow.next;',
      '        fast = fast.next.next;',
      '    }',
      '    return slow;',
      '}',
    ],
    javascript: [
      'function middleNode(head) {',
      '    let slow = head, fast = head;',
      '    while (fast && fast.next) {',
      '        slow = slow.next;',
      '        fast = fast.next.next;',
      '    }',
      '    return slow;',
      '}',
    ],
    pseudocode: [
      'function findMiddle(head):',
      '    slow ← head, fast ← head',
      '    while fast ≠ NULL and fast.next ≠ NULL do',
      '        slow ← slow.next',
      '        fast ← fast.next.next',
      '    return slow',
    ],
  },
};
