/**
 * Custom Code stub registry — typed accessors over stubs.json
 * (generated by scripts/generateCustomCodeStubs.mjs; regenerate that way,
 * never edit stubs.json by hand).
 */

import stubsData from './stubs.json';

export type CustomStubLanguage = 'python' | 'cpp' | 'c' | 'java' | 'go' | 'csharp';

export type HarnessCategory =
  | 'array_in'
  | 'string_in'
  | 'number_in'
  | 'grid_in'
  | 'linked_list_in'
  | 'graph_in'
  | 'stateful_class';

export interface StubParam {
  name: string;
  type: string;
}

export interface StubMethod {
  name: string;
  params: StubParam[];
  returns: string;
}

export interface AlgorithmStubEntry {
  key: string;
  categoryId: string;
  topicId: string;
  name: string;
  harness: HarnessCategory;
  kind: 'function' | 'class';
  entry: string;
  note?: string;
  stubs: Record<CustomStubLanguage, string>;
  params?: StubParam[];
  returns?: string;
  ctorParams?: StubParam[];
  methods?: StubMethod[];
}

interface StubsFile {
  languages: CustomStubLanguage[];
  languageLabels: Record<CustomStubLanguage, string>;
  harnessCategories: Record<HarnessCategory, string>;
  algorithms: AlgorithmStubEntry[];
}

const data = stubsData as unknown as StubsFile;

export const CUSTOM_CODE_LANGUAGES: { id: CustomStubLanguage; label: string }[] =
  data.languages.map((id) => ({ id, label: data.languageLabels[id] }));

export const HARNESS_CATEGORY_DOCS: Record<HarnessCategory, string> = data.harnessCategories;

const byKey = new Map<string, AlgorithmStubEntry>(data.algorithms.map((a) => [a.key, a]));

export function getStubEntry(categoryId: string, topicId: string): AlgorithmStubEntry | undefined {
  return byKey.get(`${categoryId}.${topicId}`);
}

export function getStubText(
  categoryId: string,
  topicId: string,
  lang: CustomStubLanguage
): string | undefined {
  return byKey.get(`${categoryId}.${topicId}`)?.stubs[lang];
}

export function hasCustomStub(categoryId: string, topicId: string): boolean {
  return byKey.has(`${categoryId}.${topicId}`);
}
