export type GraphCodeLanguage =
  | 'python'
  | 'cpp'
  | 'java'
  | 'javascript'
  | 'go'
  | 'rust'
  | 'pseudocode';

export interface GraphCodeSnippets {
  [language: string]: string[];
}

export const GRAPH_SNIPPETS: Record<string, GraphCodeSnippets> = {
  bfs: {
    python: [
      'def bfs(graph, start):',
      '    visited = {start}',
      '    queue = deque([start])',
      '    while queue:',
      '        node = queue.popleft()',
      '        for neighbor in graph[node]:',
      '            if neighbor not in visited:',
      '                visited.add(neighbor)',
      '                queue.append(neighbor)',
      '    return visited',
    ],
    cpp: [
      'void bfs(const vector<vector<int>>& adj, int start) {',
      '    vector<bool> visited(adj.size(), false);',
      '    queue<int> q;',
      '    visited[start] = true;',
      '    q.push(start);',
      '    while (!q.empty()) {',
      '        int u = q.front(); q.pop();',
      '        for (int v : adj[u]) {',
      '            if (!visited[v]) {',
      '                visited[v] = true;',
      '                q.push(v);',
      '            }',
      '        }',
      '    }',
      '}',
    ],
    java: [
      'public void bfs(List<List<Integer>> adj, int start) {',
      '    boolean[] visited = new boolean[adj.size()];',
      '    Queue<Integer> queue = new LinkedList<>();',
      '    visited[start] = true;',
      '    queue.offer(start);',
      '    while (!queue.isEmpty()) {',
      '        int u = queue.poll();',
      '        for (int v : adj.get(u)) {',
      '            if (!visited[v]) {',
      '                visited[v] = true;',
      '                queue.offer(v);',
      '            }',
      '        }',
      '    }',
      '}',
    ],
    javascript: [
      'function bfs(adj, start) {',
      '    const visited = new Set([start]);',
      '    const queue = [start];',
      '    while (queue.length > 0) {',
      '        const node = queue.shift();',
      '        for (const neighbor of adj[node]) {',
      '            if (!visited.has(neighbor)) {',
      '                visited.add(neighbor);',
      '                queue.push(neighbor);',
      '            }',
      '        }',
      '    }',
      '    return visited;',
      '}',
    ],
    go: [
      'func bfs(adj map[string][]string, start string) {',
      '    visited := map[string]bool{start: true}',
      '    queue := []string{start}',
      '    for len(queue) > 0 {',
      '        node := queue[0]',
      '        queue = queue[1:]',
      '        for _, neighbor := range adj[node] {',
      '            if !visited[neighbor] {',
      '                visited[neighbor] = true',
      '                queue = append(queue, neighbor)',
      '            }',
      '        }',
      '    }',
      '}',
    ],
    rust: [
      'pub fn bfs(adj: &Vec<Vec<usize>>, start: usize) {',
      '    let mut visited = vec![false; adj.len()];',
      '    let mut queue = std::collections::VecDeque::new();',
      '    visited[start] = true;',
      '    queue.push_back(start);',
      '    while let Some(u) = queue.pop_front() {',
      '        for &v in &adj[u] {',
      '            if !visited[v] {',
      '                visited[v] = true;',
      '                queue.push_back(v);',
      '            }',
      '        }',
      '    }',
      '}',
    ],
    pseudocode: [
      'procedure BFS(G, start):',
      '    let Q be a Queue',
      '    label start as discovered',
      '    Q.enqueue(start)',
      '    while Q is not empty do',
      '        v := Q.dequeue()',
      '        for all edges from v to w in G.adjacentEdges(v) do',
      '            if w is not labeled as discovered then',
      '                label w as discovered',
      '                Q.enqueue(w)',
    ],
  },

  dfs: {
    python: [
      'def dfs(graph, node, visited=None):',
      '    if visited is None: visited = set()',
      '    visited.add(node)',
      '    for neighbor in graph[node]:',
      '        if neighbor not in visited:',
      '            dfs(graph, neighbor, visited)',
      '    return visited',
    ],
    cpp: [
      'void dfs(int u, const vector<vector<int>>& adj, vector<bool>& visited) {',
      '    visited[u] = true;',
      '    for (int v : adj[u]) {',
      '        if (!visited[v]) {',
      '            dfs(v, adj, visited);',
      '        }',
      '    }',
      '}',
    ],
    java: [
      'public void dfs(int u, List<List<Integer>> adj, boolean[] visited) {',
      '    visited[u] = true;',
      '    for (int v : adj.get(u)) {',
      '        if (!visited[v]) {',
      '            dfs(v, adj, visited);',
      '        }',
      '    }',
      '}',
    ],
    javascript: [
      'function dfs(adj, node, visited = new Set()) {',
      '    visited.add(node);',
      '    for (const neighbor of adj[node]) {',
      '        if (!visited.has(neighbor)) {',
      '            dfs(adj, neighbor, visited);',
      '        }',
      '    }',
      '    return visited;',
      '}',
    ],
    pseudocode: [
      'procedure DFS(G, v):',
      '    label v as discovered',
      '    for all directed edges from v to w that are in G.adjacentEdges(v) do',
      '        if vertex w is not labeled as discovered then',
      '            recursively call DFS(G, w)',
    ],
  },

  dijkstra: {
    python: [
      'def dijkstra(graph, start):',
      '    dist = {node: float("inf") for node in graph}',
      '    dist[start] = 0',
      '    pq = [(0, start)]',
      '    while pq:',
      '        d, u = heapq.heappop(pq)',
      '        if d > dist[u]: continue',
      '        for v, weight in graph[u].items():',
      '            if dist[u] + weight < dist[v]:',
      '                dist[v] = dist[u] + weight',
      '                heapq.heappush(pq, (dist[v], v))',
      '    return dist',
    ],
    cpp: [
      'vector<int> dijkstra(int n, const vector<vector<pair<int, int>>>& adj, int start) {',
      '    vector<int> dist(n, INT_MAX);',
      '    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<>> pq;',
      '    dist[start] = 0;',
      '    pq.push({0, start});',
      '    while (!pq.empty()) {',
      '        auto [d, u] = pq.top(); pq.pop();',
      '        if (d > dist[u]) continue;',
      '        for (auto [v, w] : adj[u]) {',
      '            if (dist[u] + w < dist[v]) {',
      '                dist[v] = dist[u] + w;',
      '                pq.push({dist[v], v});',
      '            }',
      '        }',
      '    }',
      '    return dist;',
      '}',
    ],
    java: [
      'public int[] dijkstra(int n, List<List<int[]>> adj, int start) {',
      '    int[] dist = new int[n];',
      '    Arrays.fill(dist, Integer.MAX_VALUE);',
      '    PriorityQueue<int[]> pq = new PriorityQueue<>(Comparator.comparingInt(a -> a[1]));',
      '    dist[start] = 0;',
      '    pq.offer(new int[]{start, 0});',
      '    while (!pq.isEmpty()) {',
      '        int[] curr = pq.poll();',
      '        int u = curr[0], d = curr[1];',
      '        if (d > dist[u]) continue;',
      '        for (int[] edge : adj.get(u)) {',
      '            int v = edge[0], w = edge[1];',
      '            if (dist[u] + w < dist[v]) {',
      '                dist[v] = dist[u] + w;',
      '                pq.offer(new int[]{v, dist[v]});',
      '            }',
      '        }',
      '    }',
      '    return dist;',
      '}',
    ],
    javascript: [
      'function dijkstra(graph, start) {',
      '    const dist = {};',
      '    for (const node in graph) dist[node] = Infinity;',
      '    dist[start] = 0;',
      '    const pq = [[start, 0]];',
      '    while (pq.length > 0) {',
      '        pq.sort((a, b) => a[1] - b[1]);',
      '        const [u, d] = pq.shift();',
      '        if (d > dist[u]) continue;',
      '        for (const [v, w] of graph[u]) {',
      '            if (dist[u] + w < dist[v]) {',
      '                dist[v] = dist[u] + w;',
      '                pq.push([v, dist[v]]);',
      '            }',
      '        }',
      '    }',
      '    return dist;',
      '}',
    ],
    pseudocode: [
      'function Dijkstra(Graph, source):',
      '    for each vertex v in Graph:',
      '        dist[v] := INFINITY, prev[v] := UNDEFINED',
      '    dist[source] := 0',
      '    Q := all vertices in Graph',
      '    while Q is not empty:',
      '        u := vertex in Q with min dist[u]',
      '        remove u from Q',
      '        for each neighbor v of u:',
      '            alt := dist[u] + length(u, v)',
      '            if alt < dist[v]:',
      '                dist[v] := alt, prev[v] := u',
      '    return dist, prev',
    ],
  },

  prim: {
    python: [
      'def prim_mst(graph, start):',
      '    visited = {start}',
      '    edges = [(cost, start, to) for to, cost in graph[start].items()]',
      '    heapq.heapify(edges)',
      '    mst = []',
      '    while edges:',
      '        cost, frm, to = heapq.heappop(edges)',
      '        if to not in visited:',
      '            visited.add(to)',
      '            mst.append((frm, to, cost))',
      '            for next_to, next_cost in graph[to].items():',
      '                if next_to not in visited:',
      '                    heapq.heappush(edges, (next_cost, to, next_to))',
      '    return mst',
    ],
    cpp: [
      'int primMST(int n, const vector<vector<pair<int, int>>>& adj) {',
      '    vector<bool> inMST(n, false);',
      '    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<>> pq;',
      '    pq.push({0, 0});',
      '    int totalWeight = 0;',
      '    while (!pq.empty()) {',
      '        auto [weight, u] = pq.top(); pq.pop();',
      '        if (inMST[u]) continue;',
      '        inMST[u] = true;',
      '        totalWeight += weight;',
      '        for (auto [v, w] : adj[u]) {',
      '            if (!inMST[v]) pq.push({w, v});',
      '        }',
      '    }',
      '    return totalWeight;',
      '}',
    ],
    pseudocode: [
      'function Prim(Graph, start):',
      '    MST := empty set',
      '    Visited := {start}',
      '    while Visited does not contain all vertices:',
      '        find minimum weight edge (u, v) such that u in Visited and v not in Visited',
      '        add (u, v) to MST',
      '        add v to Visited',
      '    return MST',
    ],
  },

  topoSort: {
    python: [
      'def topological_sort(graph, in_degree):',
      '    queue = deque([u for u in graph if in_degree[u] == 0])',
      '    topo_order = []',
      '    while queue:',
      '        u = queue.popleft()',
      '        topo_order.append(u)',
      '        for v in graph[u]:',
      '            in_degree[v] -= 1',
      '            if in_degree[v] == 0:',
      '                queue.append(v)',
      '    return topo_order',
    ],
    cpp: [
      'vector<int> topologicalSort(int n, const vector<vector<int>>& adj) {',
      '    vector<int> inDegree(n, 0);',
      '    for (int u = 0; u < n; ++u) for (int v : adj[u]) inDegree[v]++;',
      '    queue<int> q;',
      '    for (int i = 0; i < n; ++i) if (inDegree[i] == 0) q.push(i);',
      '    vector<int> order;',
      '    while (!q.empty()) {',
      '        int u = q.front(); q.pop();',
      '        order.push_back(u);',
      '        for (int v : adj[u]) {',
      '            if (--inDegree[v] == 0) q.push(v);',
      '        }',
      '    }',
      '    return order;',
      '}',
    ],
    pseudocode: [
      'function KahnTopoSort(Graph):',
      '    L := Empty list that will contain the sorted elements',
      '    S := Set of all nodes with no incoming edge',
      '    while S is not empty do',
      '        remove a node n from S',
      '        append n to L',
      '        for each node m with an edge e from n to m do',
      '            remove edge e from the graph',
      '            if m has no other incoming edges then',
      '                insert m into S',
      '    return L',
    ],
  },

  kruskal: {
    pseudocode: [
      'function Kruskal(Graph):',
      '    sort all edges by weight (ascending)',
      '    initialize DSU with each vertex as its own component',
      '    MST_edges = []',
      '    for each edge (u, v, w) in sorted order:',
      '        if DSU.find(u) ≠ DSU.find(v):   // no cycle',
      '            MST_edges.add((u, v, w))',
      '            DSU.union(u, v)',
      '        else: skip (would create cycle)',
      '    return MST_edges',
    ],
    python: [
      'def kruskal(vertices, edges):',
      '    edges.sort(key=lambda e: e[2])',
      '    parent = {v: v for v in vertices}',
      '    rank = {v: 0 for v in vertices}',
      '    def find(x):',
      '        if parent[x] != x: parent[x] = find(parent[x])',
      '        return parent[x]',
      '    def union(x, y):',
      '        rx, ry = find(x), find(y)',
      '        if rx == ry: return False',
      '        if rank[rx] < rank[ry]: parent[rx] = ry',
      '        elif rank[rx] > rank[ry]: parent[ry] = rx',
      '        else: parent[ry] = rx; rank[rx] += 1',
      '        return True',
      '    mst, cost = [], 0',
      '    for u, v, w in edges:',
      '        if union(u, v):',
      '            mst.append((u, v, w)); cost += w',
      '    return mst, cost',
    ],
    cpp: [
      'struct DSU { vector<int> p, r;',
      '  DSU(int n): p(n), r(n,0) { iota(p.begin(),p.end(),0); }',
      '  int find(int x) { return p[x]==x?x:p[x]=find(p[x]); }',
      '  bool unite(int x,int y) {',
      '    x=find(x); y=find(y); if(x==y) return false;',
      '    if(r[x]<r[y]) swap(x,y);',
      '    p[y]=x; if(r[x]==r[y]) r[x]++;',
      '    return true; }',
      '};',
      'vector<tuple<int,int,int>> kruskal(',
      '    int n, vector<tuple<int,int,int>>& edges) {',
      '  sort(edges.begin(),edges.end());',
      '  DSU dsu(n);',
      '  vector<tuple<int,int,int>> mst;',
      '  for(auto& [w,u,v]: edges)',
      '    if(dsu.unite(u,v)) mst.push_back({w,u,v});',
      '  return mst;',
      '}',
    ],
    java: [
      'int[] parent, rank;',
      'int find(int x) {',
      '    if (parent[x] != x) parent[x] = find(parent[x]);',
      '    return parent[x];',
      '}',
      'boolean union(int x, int y) {',
      '    int rx = find(x), ry = find(y);',
      '    if (rx == ry) return false;',
      '    if (rank[rx] < rank[ry]) { parent[rx] = ry; }',
      '    else if (rank[rx] > rank[ry]) { parent[ry] = rx; }',
      '    else { parent[ry] = rx; rank[rx]++; }',
      '    return true;',
      '}',
      'List<int[]> kruskal(int n, int[][] edges) {',
      '    Arrays.sort(edges, (a,b) -> a[2]-b[2]);',
      '    parent = new int[n]; rank = new int[n];',
      '    for(int i=0;i<n;i++) parent[i]=i;',
      '    List<int[]> mst = new ArrayList<>();',
      '    for (int[] e : edges)',
      '        if (union(e[0],e[1])) mst.add(e);',
      '    return mst;',
      '}',
    ],
    go: [
      'type DSU struct { parent, rank []int }',
      'func newDSU(n int) *DSU {',
      '    d := &DSU{make([]int,n), make([]int,n)}',
      '    for i := range d.parent { d.parent[i] = i }',
      '    return d',
      '}',
      'func (d *DSU) find(x int) int {',
      '    if d.parent[x] != x { d.parent[x] = d.find(d.parent[x]) }',
      '    return d.parent[x]',
      '}',
      'func (d *DSU) union(x, y int) bool {',
      '    rx, ry := d.find(x), d.find(y)',
      '    if rx == ry { return false }',
      '    if d.rank[rx] < d.rank[ry] { rx, ry = ry, rx }',
      '    d.parent[ry] = rx',
      '    if d.rank[rx] == d.rank[ry] { d.rank[rx]++ }',
      '    return true',
      '}',
    ],
  },

  bellmanFord: {
    pseudocode: [
      'function BellmanFord(Graph, source):',
      '    dist[source] = 0; dist[all others] = ∞',
      '    repeat V-1 times:',
      '        for each edge (u, v, w) in Graph.edges:',
      '            if dist[u] + w < dist[v]:',
      '                dist[v] = dist[u] + w   // relax',
      '    // Negative cycle detection:',
      '    for each edge (u, v, w):',
      '        if dist[u] + w < dist[v]:',
      '            report "NEGATIVE CYCLE DETECTED"',
      '    return dist',
    ],
    python: [
      'def bellman_ford(graph, source):',
      '    dist = {v: float("inf") for v in graph}',
      '    dist[source] = 0',
      '    V = len(graph)',
      '    for _ in range(V - 1):',
      '        for u, v, w in graph.edges:',
      '            if dist[u] + w < dist[v]:',
      '                dist[v] = dist[u] + w',
      '    for u, v, w in graph.edges:',
      '        if dist[u] + w < dist[v]:',
      '            raise ValueError("Negative cycle!")',
      '    return dist',
    ],
    cpp: [
      'vector<int> bellman_ford(int n, vector<tuple<int,int,int>>& edges, int src) {',
      '    vector<int> dist(n, INT_MAX);',
      '    dist[src] = 0;',
      '    for (int i = 0; i < n-1; i++) {',
      '        for (auto [u,v,w] : edges) {',
      '            if (dist[u] != INT_MAX && dist[u]+w < dist[v])',
      '                dist[v] = dist[u]+w;',
      '        }',
      '    }',
      '    for (auto [u,v,w] : edges)',
      '        if (dist[u] != INT_MAX && dist[u]+w < dist[v])',
      '            throw runtime_error("Negative cycle");',
      '    return dist;',
      '}',
    ],
    java: [
      'int[] bellmanFord(int V, int[][] edges, int src) {',
      '    int[] dist = new int[V];',
      '    Arrays.fill(dist, Integer.MAX_VALUE);',
      '    dist[src] = 0;',
      '    for (int i = 0; i < V - 1; i++) {',
      '        for (int[] e : edges) {',
      '            if (dist[e[0]] != Integer.MAX_VALUE',
      '                && dist[e[0]] + e[2] < dist[e[1]])',
      '                dist[e[1]] = dist[e[0]] + e[2];',
      '        }',
      '    }',
      '    for (int[] e : edges)',
      '        if (dist[e[0]] + e[2] < dist[e[1]])',
      '            throw new RuntimeException("Negative cycle");',
      '    return dist;',
      '}',
    ],
    go: [
      'func bellmanFord(V int, edges [][3]int, src int) ([]int, bool) {',
      '    dist := make([]int, V)',
      '    for i := range dist { dist[i] = math.MaxInt32 }',
      '    dist[src] = 0',
      '    for i := 0; i < V-1; i++ {',
      '        for _, e := range edges {',
      '            u, v, w := e[0], e[1], e[2]',
      '            if dist[u] != math.MaxInt32 && dist[u]+w < dist[v] {',
      '                dist[v] = dist[u] + w',
      '            }',
      '        }',
      '    }',
      '    for _, e := range edges {',
      '        if dist[e[0]]+e[2] < dist[e[1]] { return nil, true }',
      '    }',
      '    return dist, false',
      '}',
    ],
  },

  aStar: {
    pseudocode: [
      'function A_Star(grid, start, goal):',
      '    open_set = {start}',
      '    g[start] = 0; h[start] = heuristic(start, goal)',
      '    f[start] = g[start] + h[start]',
      '    while open_set is not empty:',
      '        current = node in open_set with lowest f',
      '        if current == goal: return reconstruct_path()',
      '        open_set.remove(current)',
      '        closed_set.add(current)',
      '        for each neighbor of current:',
      '            if neighbor in closed_set: skip',
      '            tentative_g = g[current] + cost(current, neighbor)',
      '            if tentative_g < g[neighbor]:',
      '                parent[neighbor] = current',
      '                g[neighbor] = tentative_g',
      '                f[neighbor] = g[neighbor] + h[neighbor]',
      '                if neighbor not in open_set: open_set.add(neighbor)',
      '    return NO_PATH',
    ],
    python: [
      'import heapq',
      'def a_star(grid, start, goal):',
      '    def h(a, b): return abs(a[0]-b[0]) + abs(a[1]-b[1])',
      '    open_set = [(h(start,goal), 0, start)]',
      '    g = {start: 0}; parent = {start: None}',
      '    while open_set:',
      '        _, cost, cur = heapq.heappop(open_set)',
      '        if cur == goal:',
      '            path = []',
      '            while cur: path.append(cur); cur = parent[cur]',
      '            return path[::-1]',
      '        for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:',
      '            nb = (cur[0]+dr, cur[1]+dc)',
      '            if not in_bounds(nb) or is_wall(nb): continue',
      '            new_g = g[cur] + 1',
      '            if new_g < g.get(nb, float("inf")):',
      '                g[nb] = new_g; parent[nb] = cur',
      '                heapq.heappush(open_set,(new_g+h(nb,goal),new_g,nb))',
      '    return None',
    ],
    cpp: [
      'struct Cell { int r, c; };',
      'auto manhattan = [](Cell a, Cell b) {',
      '    return abs(a.r-b.r) + abs(a.c-b.c); };',
      'vector<Cell> a_star(vector<string>& grid, Cell s, Cell g) {',
      '    int R=grid.size(), C=grid[0].size();',
      '    map<pair<int,int>,int> G;',
      '    map<pair<int,int>,pair<int,int>> parent;',
      '    auto key=[](Cell c){return make_pair(c.r,c.c);};',
      '    priority_queue<tuple<int,int,Cell>,',
      '        vector<tuple<int,int,Cell>>, greater<>> pq;',
      '    G[key(s)]=0; pq.push({manhattan(s,g),0,s});',
      '    while(!pq.empty()) {',
      '        auto [f,cost,cur] = pq.top(); pq.pop();',
      '        if(cur.r==g.r && cur.c==g.c) break;',
      '        for(auto [dr,dc]: vector<pair<int,int>>{{-1,0},{1,0},{0,-1},{0,1}}) {',
      '            Cell nb{cur.r+dr,cur.c+dc};',
      '            if(nb.r<0||nb.r>=R||nb.c<0||nb.c>=C) continue;',
      '            if(grid[nb.r][nb.c]==\'#\') continue;',
      '            int ng=cost+1;',
      '            if(!G.count(key(nb))||ng<G[key(nb)]) {',
      '                G[key(nb)]=ng; parent[key(nb)]=key(cur);',
      '                pq.push({ng+manhattan(nb,g),ng,nb}); }}}',
      '    // reconstruct path...',
      '}',
    ],
    java: [
      'record Cell(int r, int c) {}',
      'int h(Cell a, Cell b) {',
      '    return Math.abs(a.r()-b.r()) + Math.abs(a.c()-b.c()); }',
      'List<Cell> aStar(char[][] grid, Cell start, Cell goal) {',
      '    Map<Cell,Integer> g = new HashMap<>();',
      '    Map<Cell,Cell> parent = new HashMap<>();',
      '    PriorityQueue<int[]> pq = new PriorityQueue<>(',
      '        Comparator.comparingInt(x -> x[0]));',
      '    g.put(start, 0);',
      '    pq.offer(new int[]{h(start,goal), start.r(), start.c()});',
      '    while (!pq.isEmpty()) {',
      '        int[] cur = pq.poll();',
      '        Cell c = new Cell(cur[1], cur[2]);',
      '        if (c.equals(goal)) return reconstruct(parent, goal);',
      '        for (int[] d: new int[][]{{-1,0},{1,0},{0,-1},{0,1}}) {',
      '            Cell nb = new Cell(c.r()+d[0], c.c()+d[1]);',
      '            if (!inBounds(grid, nb) || grid[nb.r()][nb.c()]==\'#\') continue;',
      '            int ng = g.get(c) + 1;',
      '            if (ng < g.getOrDefault(nb, Integer.MAX_VALUE)) {',
      '                g.put(nb, ng); parent.put(nb, c);',
      '                pq.offer(new int[]{ng+h(nb,goal),nb.r(),nb.c()}); }}}',
      '    return Collections.emptyList(); }',
    ],
    go: [
      'type Cell struct{ r, c int }',
      'func h(a, b Cell) int {',
      '    return abs(a.r-b.r) + abs(a.c-b.c)',
      '}',
      'func aStar(grid []string, start, goal Cell) []Cell {',
      '    gScore := map[Cell]int{start: 0}',
      '    parent := map[Cell]Cell{}',
      '    pq := &MinHeap{{h(start,goal), 0, start}}',
      '    heap.Init(pq)',
      '    for pq.Len() > 0 {',
      '        item := heap.Pop(pq).(Item)',
      '        cur := item.cell',
      '        if cur == goal { return reconstruct(parent, goal) }',
      '        for _, d := range [][2]int{{-1,0},{1,0},{0,-1},{0,1}} {',
      '            nb := Cell{cur.r+d[0], cur.c+d[1]}',
      '            if !inBounds(grid, nb) || grid[nb.r][nb.c] == \'#\' { continue }',
      '            ng := gScore[cur] + 1',
      '            if prev, ok := gScore[nb]; !ok || ng < prev {',
      '                gScore[nb] = ng; parent[nb] = cur',
      '                heap.Push(pq, Item{ng+h(nb,goal), ng, nb}) }}}',
      '    return nil',
      '}',
    ],
  },
};
