export type GraphCodeLanguage =
  | 'python'
  | 'cpp'
  | 'java'
  | 'javascript'
  | 'go'
  | 'rust'
  | 'pseudocode';

export interface GraphCodeSnippets {
  [language: string]: string[];
}

export const GRAPH_SNIPPETS: Record<string, GraphCodeSnippets> = {
  bfs: {
    python: [
      'def bfs(graph, start):',
      '    visited = {start}',
      '    queue = deque([start])',
      '    while queue:',
      '        node = queue.popleft()',
      '        for neighbor in graph[node]:',
      '            if neighbor not in visited:',
      '                visited.add(neighbor)',
      '                queue.append(neighbor)',
      '    return visited',
    ],
    cpp: [
      'void bfs(const vector<vector<int>>& adj, int start) {',
      '    vector<bool> visited(adj.size(), false);',
      '    queue<int> q;',
      '    visited[start] = true;',
      '    q.push(start);',
      '    while (!q.empty()) {',
      '        int u = q.front(); q.pop();',
      '        for (int v : adj[u]) {',
      '            if (!visited[v]) {',
      '                visited[v] = true;',
      '                q.push(v);',
      '            }',
      '        }',
      '    }',
      '}',
    ],
    java: [
      'public void bfs(List<List<Integer>> adj, int start) {',
      '    boolean[] visited = new boolean[adj.size()];',
      '    Queue<Integer> queue = new LinkedList<>();',
      '    visited[start] = true;',
      '    queue.offer(start);',
      '    while (!queue.isEmpty()) {',
      '        int u = queue.poll();',
      '        for (int v : adj.get(u)) {',
      '            if (!visited[v]) {',
      '                visited[v] = true;',
      '                queue.offer(v);',
      '            }',
      '        }',
      '    }',
      '}',
    ],
    javascript: [
      'function bfs(adj, start) {',
      '    const visited = new Set([start]);',
      '    const queue = [start];',
      '    while (queue.length > 0) {',
      '        const node = queue.shift();',
      '        for (const neighbor of adj[node]) {',
      '            if (!visited.has(neighbor)) {',
      '                visited.add(neighbor);',
      '                queue.push(neighbor);',
      '            }',
      '        }',
      '    }',
      '    return visited;',
      '}',
    ],
    go: [
      'func bfs(adj map[string][]string, start string) {',
      '    visited := map[string]bool{start: true}',
      '    queue := []string{start}',
      '    for len(queue) > 0 {',
      '        node := queue[0]',
      '        queue = queue[1:]',
      '        for _, neighbor := range adj[node] {',
      '            if !visited[neighbor] {',
      '                visited[neighbor] = true',
      '                queue = append(queue, neighbor)',
      '            }',
      '        }',
      '    }',
      '}',
    ],
    rust: [
      'pub fn bfs(adj: &Vec<Vec<usize>>, start: usize) {',
      '    let mut visited = vec![false; adj.len()];',
      '    let mut queue = std::collections::VecDeque::new();',
      '    visited[start] = true;',
      '    queue.push_back(start);',
      '    while let Some(u) = queue.pop_front() {',
      '        for &v in &adj[u] {',
      '            if !visited[v] {',
      '                visited[v] = true;',
      '                queue.push_back(v);',
      '            }',
      '        }',
      '    }',
      '}',
    ],
    pseudocode: [
      'procedure BFS(G, start):',
      '    let Q be a Queue',
      '    label start as discovered',
      '    Q.enqueue(start)',
      '    while Q is not empty do',
      '        v := Q.dequeue()',
      '        for all edges from v to w in G.adjacentEdges(v) do',
      '            if w is not labeled as discovered then',
      '                label w as discovered',
      '                Q.enqueue(w)',
    ],
  },

  dfs: {
    python: [
      'def dfs(graph, node, visited=None):',
      '    if visited is None: visited = set()',
      '    visited.add(node)',
      '    for neighbor in graph[node]:',
      '        if neighbor not in visited:',
      '            dfs(graph, neighbor, visited)',
      '    return visited',
    ],
    cpp: [
      'void dfs(int u, const vector<vector<int>>& adj, vector<bool>& visited) {',
      '    visited[u] = true;',
      '    for (int v : adj[u]) {',
      '        if (!visited[v]) {',
      '            dfs(v, adj, visited);',
      '        }',
      '    }',
      '}',
    ],
    java: [
      'public void dfs(int u, List<List<Integer>> adj, boolean[] visited) {',
      '    visited[u] = true;',
      '    for (int v : adj.get(u)) {',
      '        if (!visited[v]) {',
      '            dfs(v, adj, visited);',
      '        }',
      '    }',
      '}',
    ],
    javascript: [
      'function dfs(adj, node, visited = new Set()) {',
      '    visited.add(node);',
      '    for (const neighbor of adj[node]) {',
      '        if (!visited.has(neighbor)) {',
      '            dfs(adj, neighbor, visited);',
      '        }',
      '    }',
      '    return visited;',
      '}',
    ],
    pseudocode: [
      'procedure DFS(G, v):',
      '    label v as discovered',
      '    for all directed edges from v to w that are in G.adjacentEdges(v) do',
      '        if vertex w is not labeled as discovered then',
      '            recursively call DFS(G, w)',
    ],
  },

  dijkstra: {
    python: [
      'def dijkstra(graph, start):',
      '    dist = {node: float("inf") for node in graph}',
      '    dist[start] = 0',
      '    pq = [(0, start)]',
      '    while pq:',
      '        d, u = heapq.heappop(pq)',
      '        if d > dist[u]: continue',
      '        for v, weight in graph[u].items():',
      '            if dist[u] + weight < dist[v]:',
      '                dist[v] = dist[u] + weight',
      '                heapq.heappush(pq, (dist[v], v))',
      '    return dist',
    ],
    cpp: [
      'vector<int> dijkstra(int n, const vector<vector<pair<int, int>>>& adj, int start) {',
      '    vector<int> dist(n, INT_MAX);',
      '    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<>> pq;',
      '    dist[start] = 0;',
      '    pq.push({0, start});',
      '    while (!pq.empty()) {',
      '        auto [d, u] = pq.top(); pq.pop();',
      '        if (d > dist[u]) continue;',
      '        for (auto [v, w] : adj[u]) {',
      '            if (dist[u] + w < dist[v]) {',
      '                dist[v] = dist[u] + w;',
      '                pq.push({dist[v], v});',
      '            }',
      '        }',
      '    }',
      '    return dist;',
      '}',
    ],
    java: [
      'public int[] dijkstra(int n, List<List<int[]>> adj, int start) {',
      '    int[] dist = new int[n];',
      '    Arrays.fill(dist, Integer.MAX_VALUE);',
      '    PriorityQueue<int[]> pq = new PriorityQueue<>(Comparator.comparingInt(a -> a[1]));',
      '    dist[start] = 0;',
      '    pq.offer(new int[]{start, 0});',
      '    while (!pq.isEmpty()) {',
      '        int[] curr = pq.poll();',
      '        int u = curr[0], d = curr[1];',
      '        if (d > dist[u]) continue;',
      '        for (int[] edge : adj.get(u)) {',
      '            int v = edge[0], w = edge[1];',
      '            if (dist[u] + w < dist[v]) {',
      '                dist[v] = dist[u] + w;',
      '                pq.offer(new int[]{v, dist[v]});',
      '            }',
      '        }',
      '    }',
      '    return dist;',
      '}',
    ],
    javascript: [
      'function dijkstra(graph, start) {',
      '    const dist = {};',
      '    for (const node in graph) dist[node] = Infinity;',
      '    dist[start] = 0;',
      '    const pq = [[start, 0]];',
      '    while (pq.length > 0) {',
      '        pq.sort((a, b) => a[1] - b[1]);',
      '        const [u, d] = pq.shift();',
      '        if (d > dist[u]) continue;',
      '        for (const [v, w] of graph[u]) {',
      '            if (dist[u] + w < dist[v]) {',
      '                dist[v] = dist[u] + w;',
      '                pq.push([v, dist[v]]);',
      '            }',
      '        }',
      '    }',
      '    return dist;',
      '}',
    ],
    pseudocode: [
      'function Dijkstra(Graph, source):',
      '    for each vertex v in Graph:',
      '        dist[v] := INFINITY, prev[v] := UNDEFINED',
      '    dist[source] := 0',
      '    Q := all vertices in Graph',
      '    while Q is not empty:',
      '        u := vertex in Q with min dist[u]',
      '        remove u from Q',
      '        for each neighbor v of u:',
      '            alt := dist[u] + length(u, v)',
      '            if alt < dist[v]:',
      '                dist[v] := alt, prev[v] := u',
      '    return dist, prev',
    ],
  },

  prim: {
    python: [
      'def prim_mst(graph, start):',
      '    visited = {start}',
      '    edges = [(cost, start, to) for to, cost in graph[start].items()]',
      '    heapq.heapify(edges)',
      '    mst = []',
      '    while edges:',
      '        cost, frm, to = heapq.heappop(edges)',
      '        if to not in visited:',
      '            visited.add(to)',
      '            mst.append((frm, to, cost))',
      '            for next_to, next_cost in graph[to].items():',
      '                if next_to not in visited:',
      '                    heapq.heappush(edges, (next_cost, to, next_to))',
      '    return mst',
    ],
    cpp: [
      'int primMST(int n, const vector<vector<pair<int, int>>>& adj) {',
      '    vector<bool> inMST(n, false);',
      '    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<>> pq;',
      '    pq.push({0, 0});',
      '    int totalWeight = 0;',
      '    while (!pq.empty()) {',
      '        auto [weight, u] = pq.top(); pq.pop();',
      '        if (inMST[u]) continue;',
      '        inMST[u] = true;',
      '        totalWeight += weight;',
      '        for (auto [v, w] : adj[u]) {',
      '            if (!inMST[v]) pq.push({w, v});',
      '        }',
      '    }',
      '    return totalWeight;',
      '}',
    ],
    pseudocode: [
      'function Prim(Graph, start):',
      '    MST := empty set',
      '    Visited := {start}',
      '    while Visited does not contain all vertices:',
      '        find minimum weight edge (u, v) such that u in Visited and v not in Visited',
      '        add (u, v) to MST',
      '        add v to Visited',
      '    return MST',
    ],
  },

  topoSort: {
    python: [
      'def topological_sort(graph, in_degree):',
      '    queue = deque([u for u in graph if in_degree[u] == 0])',
      '    topo_order = []',
      '    while queue:',
      '        u = queue.popleft()',
      '        topo_order.append(u)',
      '        for v in graph[u]:',
      '            in_degree[v] -= 1',
      '            if in_degree[v] == 0:',
      '                queue.append(v)',
      '    return topo_order',
    ],
    cpp: [
      'vector<int> topologicalSort(int n, const vector<vector<int>>& adj) {',
      '    vector<int> inDegree(n, 0);',
      '    for (int u = 0; u < n; ++u) for (int v : adj[u]) inDegree[v]++;',
      '    queue<int> q;',
      '    for (int i = 0; i < n; ++i) if (inDegree[i] == 0) q.push(i);',
      '    vector<int> order;',
      '    while (!q.empty()) {',
      '        int u = q.front(); q.pop();',
      '        order.push_back(u);',
      '        for (int v : adj[u]) {',
      '            if (--inDegree[v] == 0) q.push(v);',
      '        }',
      '    }',
      '    return order;',
      '}',
    ],
    pseudocode: [
      'function KahnTopoSort(Graph):',
      '    L := Empty list that will contain the sorted elements',
      '    S := Set of all nodes with no incoming edge',
      '    while S is not empty do',
      '        remove a node n from S',
      '        append n to L',
      '        for each node m with an edge e from n to m do',
      '            remove edge e from the graph',
      '            if m has no other incoming edges then',
      '                insert m into S',
      '    return L',
    ],
  },
};
