export type BSCodeLanguage =
  | 'python'
  | 'cpp'
  | 'java'
  | 'javascript'
  | 'go'
  | 'rust'
  | 'pseudocode';

export interface BSCodeSnippets {
  [language: string]: string[];
}

export const BINARY_SEARCH_SNIPPETS: Record<string, BSCodeSnippets> = {
  binarySearch: {
    python: [
      'def binary_search(arr, target):',
      '    left, right = 0, len(arr) - 1',
      '    while left <= right:',
      '        mid = left + (right - left) // 2',
      '        if arr[mid] == target:',
      '            return mid',
      '        elif arr[mid] < target:',
      '            left = mid + 1',
      '        else:',
      '            right = mid - 1',
      '    return -1',
    ],
    cpp: [
      'int binarySearch(const vector<int>& arr, int target) {',
      '    int left = 0, right = arr.size() - 1;',
      '    while (left <= right) {',
      '        int mid = left + (right - left) / 2;',
      '        if (arr[mid] == target) return mid;',
      '        else if (arr[mid] < target) left = mid + 1;',
      '        else right = mid - 1;',
      '    }',
      '    return -1;',
      '}',
    ],
    java: [
      'public int binarySearch(int[] arr, int target) {',
      '    int left = 0, right = arr.length - 1;',
      '    while (left <= right) {',
      '        int mid = left + (right - left) / 2;',
      '        if (arr[mid] == target) return mid;',
      '        else if (arr[mid] < target) left = mid + 1;',
      '        else right = mid - 1;',
      '    }',
      '    return -1;',
      '}',
    ],
    javascript: [
      'function binarySearch(arr, target) {',
      '    let left = 0, right = arr.length - 1;',
      '    while (left <= right) {',
      '        const mid = Math.floor(left + (right - left) / 2);',
      '        if (arr[mid] === target) return mid;',
      '        else if (arr[mid] < target) left = mid + 1;',
      '        else right = mid - 1;',
      '    }',
      '    return -1;',
      '}',
    ],
    go: [
      'func binarySearch(arr []int, target int) int {',
      '    left, right := 0, len(arr)-1',
      '    for left <= right {',
      '        mid := left + (right-left)/2',
      '        if arr[mid] == target { return mid }',
      '        if arr[mid] < target { left = mid + 1 } else { right = mid - 1 }',
      '    }',
      '    return -1',
      '}',
    ],
    rust: [
      'pub fn binary_search(arr: &[i32], target: i32) -> Option<usize> {',
      '    let mut left = 0;',
      '    let mut right = arr.len().checked_sub(1)?;',
      '    while left <= right {',
      '        let mid = left + (right - left) / 2;',
      '        match arr[mid].cmp(&target) {',
      '            std::cmp::Ordering::Equal => return Some(mid),',
      '            std::cmp::Ordering::Less => left = mid + 1,',
      '            std::cmp::Ordering::Greater => {',
      '                if mid == 0 { break; }',
      '                right = mid - 1;',
      '            }',
      '        }',
      '    }',
      '    None',
      '}',
    ],
    pseudocode: [
      'function binarySearch(arr, target):',
      '    left ← 0, right ← length(arr) - 1',
      '    while left ≤ right do',
      '        mid ← left + floor((right - left) / 2)',
      '        if arr[mid] = target then return mid',
      '        else if arr[mid] < target then left ← mid + 1',
      '        else right ← mid - 1',
      '    return -1',
    ],
  },

  lowerBound: {
    python: [
      'def lower_bound(arr, target):',
      '    left, right = 0, len(arr)',
      '    while left < right:',
      '        mid = left + (right - left) // 2',
      '        if arr[mid] >= target:',
      '            right = mid',
      '        else:',
      '            left = mid + 1',
      '    return left',
    ],
    cpp: [
      'int lowerBound(const vector<int>& arr, int target) {',
      '    int left = 0, right = arr.size();',
      '    while (left < right) {',
      '        int mid = left + (right - left) / 2;',
      '        if (arr[mid] >= target) right = mid;',
      '        else left = mid + 1;',
      '    }',
      '    return left;',
      '}',
    ],
    java: [
      'public int lowerBound(int[] arr, int target) {',
      '    int left = 0, right = arr.length;',
      '    while (left < right) {',
      '        int mid = left + (right - left) / 2;',
      '        if (arr[mid] >= target) right = mid;',
      '        else left = mid + 1;',
      '    }',
      '    return left;',
      '}',
    ],
    javascript: [
      'function lowerBound(arr, target) {',
      '    let left = 0, right = arr.length;',
      '    while (left < right) {',
      '        const mid = Math.floor(left + (right - left) / 2);',
      '        if (arr[mid] >= target) right = mid;',
      '        else left = mid + 1;',
      '    }',
      '    return left;',
      '}',
    ],
    pseudocode: [
      'function lowerBound(arr, target):',
      '    left ← 0, right ← length(arr)',
      '    while left < right do',
      '        mid ← left + floor((right - left) / 2)',
      '        if arr[mid] ≥ target then right ← mid',
      '        else left ← mid + 1',
      '    return left',
    ],
  },

  searchRotatedArray: {
    python: [
      'def search_rotated(arr, target):',
      '    left, right = 0, len(arr) - 1',
      '    while left <= right:',
      '        mid = left + (right - left) // 2',
      '        if arr[mid] == target: return mid',
      '        if arr[left] <= arr[mid]: # Left sorted',
      '            if arr[left] <= target < arr[mid]: right = mid - 1',
      '            else: left = mid + 1',
      '        else: # Right sorted',
      '            if arr[mid] < target <= arr[right]: left = mid + 1',
      '            else: right = mid - 1',
      '    return -1',
    ],
    cpp: [
      'int searchRotated(const vector<int>& nums, int target) {',
      '    int left = 0, right = nums.size() - 1;',
      '    while (left <= right) {',
      '        int mid = left + (right - left) / 2;',
      '        if (nums[mid] == target) return mid;',
      '        if (nums[left] <= nums[mid]) {',
      '            if (nums[left] <= target && target < nums[mid]) right = mid - 1;',
      '            else left = mid + 1;',
      '        } else {',
      '            if (nums[mid] < target && target <= nums[right]) left = mid + 1;',
      '            else right = mid - 1;',
      '        }',
      '    }',
      '    return -1;',
      '}',
    ],
    java: [
      'public int searchRotated(int[] nums, int target) {',
      '    int left = 0, right = nums.length - 1;',
      '    while (left <= right) {',
      '        int mid = left + (right - left) / 2;',
      '        if (nums[mid] == target) return mid;',
      '        if (nums[left] <= nums[mid]) {',
      '            if (nums[left] <= target && target < nums[mid]) right = mid - 1;',
      '            else left = mid + 1;',
      '        } else {',
      '            if (nums[mid] < target && target <= nums[right]) left = mid + 1;',
      '            else right = mid - 1;',
      '        }',
      '    }',
      '    return -1;',
      '}',
    ],
    javascript: [
      'function searchRotated(nums, target) {',
      '    let left = 0, right = nums.length - 1;',
      '    while (left <= right) {',
      '        const mid = Math.floor(left + (right - left) / 2);',
      '        if (nums[mid] === target) return mid;',
      '        if (nums[left] <= nums[mid]) {',
      '            if (nums[left] <= target && target < nums[mid]) right = mid - 1;',
      '            else left = mid + 1;',
      '        } else {',
      '            if (nums[mid] < target && target <= nums[right]) left = mid + 1;',
      '            else right = mid - 1;',
      '        }',
      '    }',
      '    return -1;',
      '}',
    ],
    pseudocode: [
      'function searchRotated(nums, target):',
      '    left ← 0, right ← length(nums) - 1',
      '    while left ≤ right do',
      '        mid ← left + floor((right - left) / 2)',
      '        if nums[mid] = target then return mid',
      '        if nums[left] ≤ nums[mid] then',
      '            if nums[left] ≤ target < nums[mid] then right ← mid - 1',
      '            else left ← mid + 1',
      '        else',
      '            if nums[mid] < target ≤ nums[right] then left ← mid + 1',
      '            else right ← mid - 1',
      '    return -1',
    ],
  },
};
