"""
Algorithm stub registry for Custom Code execution.

Loads stubs.json — the single source of truth generated by
scripts/generateCustomCodeStubs.mjs (lives in the frontend tree because the
editor consumes it at build time; the backend reads it from disk here).
"""

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Optional

_STUBS_PATH = (
    Path(__file__).resolve().parents[4]
    / "frontend"
    / "src"
    / "data"
    / "customCode"
    / "stubs.json"
)


@lru_cache()
def load_registry() -> Dict[str, Dict[str, Any]]:
    """Return a map of algorithm key -> algorithm spec."""
    with open(_STUBS_PATH, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    return {algo["key"]: algo for algo in data["algorithms"]}


def get_algorithm(algorithm_key: str) -> Optional[Dict[str, Any]]:
    """Look up an algorithm spec by its composite key (categoryId.topicId)."""
    return load_registry().get(algorithm_key)
